### ISSUE TITLE
Parsing fails if a date type is used in a record that has `deriving (eq)`

### ISSUE THREAD

**Issue by davidchappelle** [dropbox/djinni#223]
Here is an example record:

```
example_record = record {
    the_date: date;
} deriving (eq)
```

Here is the exception that I am getting:

```
Exception in thread "main" java.lang.AssertionError: Unreachable
	at djinni.JavaGenerator$$anonfun$generateRecord$2$$anonfun$apply$7$$anonfun$apply$mcV$sp$7$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$26.apply(JavaGenerator.scala:298)
	at djinni.JavaGenerator$$anonfun$generateRecord$2$$anonfun$apply$7$$anonfun$apply$mcV$sp$7$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$26.apply(JavaGenerator.scala:274)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at djinni.JavaGenerator$$anonfun$generateRecord$2$$anonfun$apply$7$$anonfun$apply$mcV$sp$7$$anonfun$apply$mcV$sp$9.apply$mcV$sp(JavaGenerator.scala:274)
	at djinni.writer.package$IndentWriter.djinni$writer$IndentWriter$$nested_(writer.scala:70)
	at djinni.writer.package$IndentWriter$$anonfun$nestedN$1.apply(writer.scala:66)
	at djinni.writer.package$IndentWriter$$anonfun$nestedN$1.apply(writer.scala:66)
	at djinni.JavaGenerator$$anonfun$generateRecord$2$$anonfun$apply$7$$anonfun$apply$mcV$sp$7.apply$mcV$sp(JavaGenerator.scala:272)
	at djinni.writer.package$IndentWriter.djinni$writer$IndentWriter$$nested_(writer.scala:70)
	at djinni.writer.package$IndentWriter.nested(writer.scala:64)
	at djinni.writer.package$IndentWriter.bracedEnd(writer.scala:80)
	at djinni.writer.package$IndentWriter$$anonfun$braced$1.apply(writer.scala:84)
	at djinni.writer.package$IndentWriter$$anonfun$braced$1.apply(writer.scala:84)
	at djinni.JavaGenerator$$anonfun$generateRecord$2$$anonfun$apply$7.apply$mcV$sp(JavaGenerator.scala:267)
	at djinni.writer.package$IndentWriter.djinni$writer$IndentWriter$$nested_(writer.scala:70)
	at djinni.writer.package$IndentWriter.nested(writer.scala:64)
	at djinni.writer.package$IndentWriter.bracedEnd(writer.scala:80)
	at djinni.writer.package$IndentWriter$$anonfun$braced$1.apply(writer.scala:84)
	at djinni.writer.package$IndentWriter$$anonfun$braced$1.apply(writer.scala:84)
	at djinni.JavaGenerator$$anonfun$generateRecord$2.apply(JavaGenerator.scala:226)
	at djinni.JavaGenerator$$anonfun$generateRecord$2.apply(JavaGenerator.scala:215)
	at djinni.JavaGenerator$$anonfun$writeJavaFile$1.apply(JavaGenerator.scala:62)
	at djinni.JavaGenerator$$anonfun$writeJavaFile$1.apply(JavaGenerator.scala:53)
	at djinni.Generator.createFile(generator.scala:244)
	at djinni.Generator.createFile(generator.scala:252)
	at djinni.JavaGenerator.writeJavaFile(JavaGenerator.scala:53)
	at djinni.JavaGenerator.generateRecord(JavaGenerator.scala:215)
	at djinni.Generator$$anonfun$generate$2.apply(generator.scala:321)
	at djinni.Generator$$anonfun$generate$2.apply(generator.scala:317)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.mutable.MutableList.foreach(MutableList.scala:29)
	at djinni.Generator.generate(generator.scala:317)
	at djinni.generatorTools.package$.generate(generator.scala:178)
	at djinni.Main$.main(Main.scala:323)
	at djinni.Main.main(Main.scala)
```

**Comment by artwyman** [comment]
Looks like eq and ord for date were never implemented (at least for Java and ObjC).  Will fix.

**Comment by kittinunf** [comment]
@artwyman I experience the same issue however generated file is correct. It is just the exception that throws out.

```
Foo = record {
  timeStamp: date;
} deriving(eq)
```

```
bool operator==(const Foo& lhs, const Foo& rhs) {
    return lhs.timeStamp == rhs.timeStamp;
}

bool operator!=(const Foo& lhs, const Foo& rhs) {
   return !(lhs == rhs);
}
```

**Comment by artwyman** [comment]
The exceptions come out of the Java and ObjC generators, so the generated C++ is fine, but the other languages haven't been generated yet.
Fix is working, and should land on github by the end of this week, along with the next batch of internal improvements from Dropbox.
