### ISSUE TITLE
Problems with leading underscores in names

### ISSUE THREAD

**Issue by kinglezhuang** [dropbox/djinni#266]
Already up to date: Djinni
Parsing...
Resolving...
Generating...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:658)
    at djinni.generatorTools.package$.firstUpper(generator.scala:86)
    at djinni.generatorTools.package$IdentStyle$$anonfun$2$$anonfun$apply$4.apply(generator.scala:106)
    at djinni.generatorTools.package$IdentStyle$$anonfun$2$$anonfun$apply$4.apply(generator.scala:106)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
    at djinni.generatorTools.package$IdentStyle$$anonfun$2.apply(generator.scala:106)
    at djinni.generatorTools.package$IdentStyle$$anonfun$2.apply(generator.scala:104)
    at djinni.JavaGenerator$$anonfun$generateRecord$2$$anonfun$apply$7$$anonfun$apply$mcV$sp$25.apply(JavaGenerator.scala:260)
    at djinni.JavaGenerator$$anonfun$generateRecord$2$$anonfun$apply$7$$anonfun$apply$mcV$sp$25.apply(JavaGenerator.scala:256)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at djinni.JavaGenerator$$anonfun$generateRecord$2$$anonfun$apply$7.apply$mcV$sp(JavaGenerator.scala:256)
    at djinni.writer.package$IndentWriter.djinni$writer$IndentWriter$$nested_(writer.scala:70)
    at djinni.writer.package$IndentWriter.nested(writer.scala:64)
    at djinni.writer.package$IndentWriter.bracedEnd(writer.scala:80)
    at djinni.writer.package$IndentWriter$$anonfun$braced$1.apply(writer.scala:84)
    at djinni.writer.package$IndentWriter$$anonfun$braced$1.apply(writer.scala:84)
    at djinni.JavaGenerator$$anonfun$generateRecord$2.apply(JavaGenerator.scala:228)
    at djinni.JavaGenerator$$anonfun$generateRecord$2.apply(JavaGenerator.scala:217)
    at djinni.JavaGenerator$$anonfun$writeJavaFile$1.apply(JavaGenerator.scala:62)
    at djinni.JavaGenerator$$anonfun$writeJavaFile$1.apply(JavaGenerator.scala:53)
    at djinni.Generator.createFile(generator.scala:246)
    at djinni.Generator.createFile(generator.scala:254)
    at djinni.JavaGenerator.writeJavaFile(JavaGenerator.scala:53)
    at djinni.JavaGenerator.generateRecord(JavaGenerator.scala:217)
    at djinni.Generator$$anonfun$generate$2.apply(generator.scala:323)
    at djinni.Generator$$anonfun$generate$2.apply(generator.scala:319)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at djinni.Generator.generate(generator.scala:319)
    at djinni.generatorTools.package$.generate(generator.scala:180)
    at djinni.Main$.main(Main.scala:331)
    at djinni.Main.main(Main.scala)

**Comment by kinglezhuang** [comment]
Building Djinni...
[info] Loading project definition from /Volumes/MacintoshHD2/Glip-Workspace/Glip-Code-Source/CoreLib/tools/djinni/src/project
[info] Updating {file:/Volumes/MacintoshHD2/Glip-Workspace/Glip-Code-Source/CoreLib/tools/djinni/src/project/}src-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to src (in build file:/Volumes/MacintoshHD2/Glip-Workspace/Glip-Code-Source/CoreLib/tools/djinni/src/)
[info] Updating {file:/Volumes/MacintoshHD2/Glip-Workspace/Glip-Code-Source/CoreLib/tools/djinni/src/}src...
[info] Resolving jline#jline;2.11 ...
[info] Done updating.
[info] Compiling 21 Scala sources to /Volumes/MacintoshHD2/Glip-Workspace/Glip-Code-Source/CoreLib/tools/djinni/src/target/scala-2.11/classes...
[success] Total time: 11 s, completed Aug 4, 2016 6:17:18 PM
[info] Wrote start script for mainClass := Some(djinni.Main) to /Volumes/MacintoshHD2/Glip-Workspace/Glip-Code-Source/CoreLib/tools/djinni/src/target/start
[success] Total time: 0 s, completed Aug 4, 2016 6:17:18 PM
Parsing...
Resolving...
Generating...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at djinni.generatorTools.package$.firstUpper(generator.scala:86)
	at djinni.generatorTools.package$IdentStyle$$anonfun$2$$anonfun$apply$4.apply(generator.scala:106)
	at djinni.generatorTools.package$IdentStyle$$anonfun$2$$anonfun$apply$4.apply(generator.scala:106)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at djinni.generatorTools.package$IdentStyle$$anonfun$2.apply(generator.scala:106)
	at djinni.generatorTools.package$IdentStyle$$anonfun$2.apply(generator.scala:104)
	at djinni.JavaGenerator$$anonfun$generateRecord$2$$anonfun$apply$7$$anonfun$apply$mcV$sp$25.apply(JavaGenerator.scala:260)
	at djinni.JavaGenerator$$anonfun$generateRecord$2$$anonfun$apply$7$$anonfun$apply$mcV$sp$25.apply(JavaGenerator.scala:256)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at djinni.JavaGenerator$$anonfun$generateRecord$2$$anonfun$apply$7.apply$mcV$sp(JavaGenerator.scala:256)
	at djinni.writer.package$IndentWriter.djinni$writer$IndentWriter$$nested_(writer.scala:70)
	at djinni.writer.package$IndentWriter.nested(writer.scala:64)
	at djinni.writer.package$IndentWriter.bracedEnd(writer.scala:80)
	at djinni.writer.package$IndentWriter$$anonfun$braced$1.apply(writer.scala:84)
	at djinni.writer.package$IndentWriter$$anonfun$braced$1.apply(writer.scala:84)
	at djinni.JavaGenerator$$anonfun$generateRecord$2.apply(JavaGenerator.scala:228)
	at djinni.JavaGenerator$$anonfun$generateRecord$2.apply(JavaGenerator.scala:217)
	at djinni.JavaGenerator$$anonfun$writeJavaFile$1.apply(JavaGenerator.scala:62)
	at djinni.JavaGenerator$$anonfun$writeJavaFile$1.apply(JavaGenerator.scala:53)
	at djinni.Generator.createFile(generator.scala:246)
	at djinni.Generator.createFile(generator.scala:254)
	at djinni.JavaGenerator.writeJavaFile(JavaGenerator.scala:53)
	at djinni.JavaGenerator.generateRecord(JavaGenerator.scala:217)
	at djinni.Generator$$anonfun$generate$2.apply(generator.scala:323)
	at djinni.Generator$$anonfun$generate$2.apply(generator.scala:319)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at djinni.Generator.generate(generator.scala:319)
	at djinni.generatorTools.package$.generate(generator.scala:180)
	at djinni.Main$.main(Main.scala:331)
	at djinni.Main.main(Main.scala)

**Comment by artwyman** [comment]
Can you provide any steps to reproduce this?  Is there a particular input file?  What version (commit) of Djinni are you using?

**Comment by kinglezhuang** [comment]
In original code base, i can use _xxx to declare record property, but now can not.
I upgraded to new version, found this issue.

**Comment by artwyman** [comment]
Oh, you're using a leading underscore on a variable name?  I'm not sure why that changed, and I can see how to make it not crash.  However, it's not really a use case which was anticipated or intentionally supported, because of Djinni's need to translate identifiers between different naming styles (like `foo_bar` to `fooBar` or `FooBar`).  An underscore in a name in a .djinni file is treated as a separator, so your variable is being parsed as 2 parts, with the first being an empty string, which can have unintended side-effects.

Out of curiousity, what did you intend/want `_xxx` to appear as when put into `fooBar` or `FooBar` style?  It looks like both end up as `Xxx`, because of the invisible "first part" of the variable.  And there's a potential for name conflicts because `_xxx` and `xxx` will translate into the same thing in some styles.

Can you tell me more about your desired use case?  If you want an underscore prefix on all of your record fields, I think you'd be better off naming the field `xxx` in Djinni, then setting the ident style to `_foo_bar` to add the prefix during generation.  If you want that prefix on only some names, such that it really needs to be part of the variable name, not the style, then I think Djinni isn't currently well set up to support that fully.  It would need a more explicit feature to support `_` as a prefix instead of a separator.  It's similarly limited if you wanted an `_` in a variable name in a style other than `foo_bar`.
