### ISSUE TITLE
Exception in thread "main".

### ISSUE THREAD

**Issue by parfenuk** [dropbox/djinni#344]
Hello!

After I composed bash script and launched it in Terminal - I got the following error:

Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/Seq
	at djinni.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

I was using Djinni before for several months, and everything was ok. But since today, when I updated my Mac OS X to version 10.13.2, it started returning this error. Any reasons what may cause it?

Thanks in advance.

EDIT: Created another project, now the error is more readable: 
Error: Could not find or load main class djinni.Main

**Comment by stidch** [comment]
I currently see the same error message. @parfenuk could you solve the problem a year ago?

**Comment by PavelSkorynin** [comment]
Just remove `djinni/src/target` and build again
