### ISSUE TITLE
Installation/compilation fails on dependencies

### ISSUE THREAD

**Issue by dair** [dropbox/djinni#362]
macOS 10.13.4 (17E199)
Tried both JDK 1.8 and fresh 10

Not sure they provide Scalactic 2.10 anymore.

```$ make djinni
cd src && ./build
Building Djinni...
[info] Loading project definition from /private/tmp/djinni/src/project
[info] Updating {file:/private/tmp/djinni/src/project/}src-build...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by sbt.ivyint.ErrorMessageAuthenticator$ (file:/Users/dair/.sbt/boot/scala-2.10.4/org.scala-sbt/sbt/0.13.5/ivy-0.13.5.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of sbt.ivyint.ErrorMessageAuthenticator$
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Resolving org.scalactic#scalactic_2.10;3.0.1 ...
[warn] 	module not found: org.scalactic#scalactic_2.10;3.0.1
[warn] ==== local: tried
[warn]   /Users/dair/.ivy2/local/org.scalactic/scalactic_2.10/3.0.1/ivys/ivy.xml
[warn] ==== ssl-typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scalactic/scalactic_2.10/3.0.1/ivys/ivy.xml
[warn] ==== ssl-maven-central: tried
[warn]   https://repo1.maven.org/maven2/org/scalactic/scalactic_2.10/3.0.1/scalactic_2.10-3.0.1.pom
[warn] ==== ssl-sbt-plugins: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scalactic/scalactic_2.10/3.0.1/ivys/ivy.xml
[info] Resolving org.pantsbuild#jarjar;1.6.4 ...
[warn] 	module not found: org.pantsbuild#jarjar;1.6.4
[warn] ==== local: tried
[warn]   /Users/dair/.ivy2/local/org.pantsbuild/jarjar/1.6.4/ivys/ivy.xml
[warn] ==== ssl-typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.pantsbuild/jarjar/1.6.4/ivys/ivy.xml
[warn] ==== ssl-maven-central: tried
[warn]   https://repo1.maven.org/maven2/org/pantsbuild/jarjar/1.6.4/jarjar-1.6.4.pom
[warn] ==== ssl-sbt-plugins: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.pantsbuild/jarjar/1.6.4/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalactic#scalactic_2.10;3.0.1: not found
[warn] 	:: org.pantsbuild#jarjar;1.6.4: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: org.scalactic#scalactic_2.10;3.0.1: not found
unresolved dependency: org.pantsbuild#jarjar;1.6.4: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:217)
	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:126)
	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:125)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:103)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:48)
	at sbt.IvySbt$$anon$3.call(Ivy.scala:57)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
	at xsbt.boot.Using$.withResource(Using.scala:11)
	at xsbt.boot.Using$.apply(Using.scala:10)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:57)
	at sbt.IvySbt.withIvy(Ivy.scala:98)
	at sbt.IvySbt.withIvy(Ivy.scala:94)
	at sbt.IvySbt$Module.withModule(Ivy.scala:115)
	at sbt.IvyActions$.update(IvyActions.scala:125)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1223)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1221)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1244)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1242)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1246)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1241)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1249)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1214)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scalactic#scalactic_2.10;3.0.1: not found
[error] unresolved dependency: org.pantsbuild#jarjar;1.6.4: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
make: *** [djinni] Error 1
```

**Comment by dair** [comment]
Today it did compile though. Sorry for disturbung.
